### ISSUE TITLE
Timeout when running tests locally gives an error

### ISSUE THREAD

**Issue by massimocode** [SMH110/Pizza-website#5]
I just cloned the repo and ran `npm install` and then `npm test` and I got the following output:
```
> pizza-website@1.0.0 test C:\projects\Pizza-website
> node node_modules/mocha/bin/mocha specs --require mocha-setup.js



  Fetch Drinks from MongoDB
    1) Should fetch the items as expected

  Fetch Pizza from MongoDB
    2) Should fetch the items as expected

  Fetch Sides from MongoDB
    3) Should fetch the items as expected


  0 passing (40s)
  3 failing

  1) Fetch Drinks from MongoDB Should fetch the items as expected:
     Error: Timeout of 20000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.


  2) Fetch Pizza from MongoDB Should fetch the items as expected:
     Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.


  3) Fetch Sides from MongoDB Should fetch the items as expected:
     Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

**Comment by SMH110** [comment]
Fixed in 196ea2b5941c47661757c0ef2a9f8a91cfd91f75
please; try to run `npm start` before you run `npm test`

**Comment by massimocode** [comment]
I'm still getting timeouts. I'm not sure why I'm getting timeouts, I would expect to get errors telling me that the server is not running.

**Comment by SMH110** [comment]
try it now 
f9bc5806cfd0da4d470bd561d9a5a8d661e2e8d8

**Comment by massimocode** [comment]
It's still not fixed. I still get a timeout.

I get the following output:
```
> pizza-website@1.0.0 test C:\projects\Pizza-website
> node node_modules/mocha/bin/mocha specs --require mocha-setup.js



  Fetch Drinks from MongoDB
{ FetchError: request to http://localhost:3000/api/drinks failed, reason: connect ECONNREFUSED 127.0.0.1:3000
    at ClientRequest.<anonymous> (C:\projects\Pizza-website\node_modules\node-fetch\index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1272:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  name: 'FetchError',
  message: 'request to http://localhost:3000/api/drinks failed, reason: connect ECONNREFUSED 127.0.0.1:3000',
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED' }
    1) Should fetch the items as expected
```

So the error message is being output, but the test still takes 20 seconds to run (it is doing nothing during that time)
